version: '3.4'

services:
  fitbit-fetch-data:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitbit-fetch-data
    volumes:
      - ./logs:/app/logs # Ensure this folder exists and is owned by user id 1000
      - ./tokens:/app/tokens # Ensure this folder exists and is owned by user id 1000
      - /etc/timezone:/etc/timezone:ro
    environment:
      - FITBIT_LOG_FILE_PATH=/app/logs/fitbit.log
      - TOKEN_FILE_PATH=/app/tokens/fitbit.token
      - OVERWRITE_LOG_FILE=True
      # VictoriaMetrics environment variables
      - VICTORIA_METRICS_URL=http://victoriametrics:8428/api/v1/import
      # Fitbit application settings
      - CLIENT_ID=your_application_client_ID # Change this to your client ID
      - CLIENT_SECRET=your_application_client_secret # Change this to your client Secret
      - DEVICENAME=Your_Device_Name # e.g. "Charge5"
      - LOCAL_TIMEZONE=Automatic # Set to "Automatic" for automatic timezone setup from user profile.
  
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    restart: unless-stopped
    ports:
      - '8428:8428' # VictoriaMetrics HTTP API port
    volumes:
      - ./victoriametrics:/victoriametrics # Ensure this folder exists to persist metrics

  grafana:
    restart: unless-stopped
    volumes:
      - './grafana:/var/lib/grafana'
    ports:
      - '3000:3000'
    container_name: grafana
    image: 'grafana/grafana:latest'
