{
 "title": "Health Stats",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket",
    "query": "buckets()\n|> map(fn: (r) => ({ \"text\": r.name, \"value\": r.name}))"
   },
   {
    "name": "TimeZone",
    "label": "Time Zone",
    "query": "America/Toronto, Asia/Kolkata, Europe/Berlin,"
   }
  ]
 },
 "panels": [
  { "title": "Recent Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device Battery Level",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Battery remaining",
     "measurement": "DeviceBatteryLevel",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DeviceBatteryLevel\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> yield(name: \"value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DeviceBatteryLevel\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> yield(name: \"value\")"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "avg_over_time(HeartRate_Intraday[$__range])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ],
     "expr": "avg_over_time(HeartRate_Intraday[$__range])"
    }
   ]
  },
  {
   "title": "RHR",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "RestingHR",
     "query": "from( bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RestingHR\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> yield(name: \"value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from( bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RestingHR\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> yield(name: \"value\")"
    }
   ]
  },
  {
   "title": "Hourly Steps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Steps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Steps_Intraday\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 6)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Steps_Intraday\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> avg_over_time(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 6)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Today's Steps",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Steps_Intraday",
     "query": "from(bucket: \"tower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Total Steps\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from(bucket: \"tower\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Total Steps\")\n  |> avg_over_time(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Spo2 Today",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "SpO2 Intraday",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SPO2_Intraday",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Intraday\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Intraday\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> avg_over_time(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SpO2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "SpO2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "SPO2",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Intraday\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> last()",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Intraday\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Sleep Pattern",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Sleep levels",
     "measurement": "Sleep Levels",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Levels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"isMainSleep\"] == \"True\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Night\" }))",
     "select": [
      [
       { "params": [ "level" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "isMainSleep", "operator": "=", "value": "True" }
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Levels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"isMainSleep\"] == \"True\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Night\" }))"
    }
   ]
  },
  {
   "title": "Last Day Total Sleep",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Total Asleep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "select": [
      [
       { "params": [ "minutesAsleep" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Pattern",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 28 },
   "targets": [
    {
     "alias": "Sleep levels",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Sleep Levels",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Levels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"isMainSleep\"] == \"True\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Levels\" }))",
     "select": [
      [
       { "params": [ "level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "isMainSleep", "operator": "=", "value": "True" }
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Levels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"isMainSleep\"] == \"True\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Levels\" }))"
    }
   ]
  },
  { "title": "Sleep Data - Long Term", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Sleep",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesDeep\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Deep\" }))\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")\n",
     "select": [
      [
       { "params": [ "minutesDeep" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesDeep\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Deep\" }))\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")\n"
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesLight\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Light\" }))\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "minutesLight" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesLight\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Light\" }))\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")"
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesREM\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"REM\" }))\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "minutesREM" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesREM\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"REM\" }))\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")"
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesAwake\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Awake\" }))\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "minutesAwake" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesAwake\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Awake\" }))\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Sleep Efficiency",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Efficiency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"efficiency\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Efficiency\" }))\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "efficiency" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"efficiency\")\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Efficiency\" }))\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Relative Skin Temperature",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Relative Skin Temp ",
     "measurement": "Skin Temperature Variation",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Skin Temperature Variation\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Skin ° Variation\"}))\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "RelativeValue" ], "type": "field" }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Skin Temperature Variation\")\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Skin ° Variation\"}))\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Average Sleep trends",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesDeep\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Deep\" }))\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "minutesDeep" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesDeep\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Deep\" }))\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")"
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesAwake\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Awake\" }))\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "minutesLight" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesAwake\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Awake\" }))\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")"
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesLight\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Light\" }))\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "minutesREM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesLight\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Light\" }))\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")"
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesREM\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"REM\" }))\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "minutesAwake" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minutesREM\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"REM\" }))\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Sleep Regularity",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "alias": "Sleep Regularity",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "Sleep Levels",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Levels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "level" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sleep Levels\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> avg_over_time(every: 1h, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Other Long Term Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Resting HR",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Resting HR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RestingHR",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RestingHR\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Resting HR\"}))\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RestingHR\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Resting HR\"}))\n  |> avg_over_time(every: 1h, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "HRV",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "DailyRmssd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HRV",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HRV\")\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: ( if r[\"_field\"] == \"dailyRmssd\" then \"Daily\" else \"Deep\")}))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "dailyRmssd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HRV\")\n  |> avg_over_time(every: 1h, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: ( if r[\"_field\"] == \"dailyRmssd\" then \"Daily\" else \"Deep\")}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Spo2 ( Avg )",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "SpO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SPO2",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"SPO2\"}))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\n  |> avg_over_time(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"SPO2\"}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Breathing Rate",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Breathing Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BreathingRate",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BreathingRate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Breathing Rate\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BreathingRate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Breathing Rate\"}))\n  |> avg_over_time(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Hourly walk heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "alias": "Hourly walk heatmap",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Steps_Intraday",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Activity Records\")\n  |> filter(fn: (r) => r[\"ActivityName\"] == \"Walk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"steps\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Activity Records\")\n  |> filter(fn: (r) => r[\"ActivityName\"] == \"Walk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"steps\")\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Activities (Steps)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "Steps" } },
   "targets": [
    {
     "measurement": "Total Steps",
     "query": "from(bucket: \"tower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Activity Records\")\n  |> filter(fn: (r) => r[\"_field\"] == \"steps\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.ActivityName}))\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "expr": "from(bucket: \"tower\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Activity Records\")\n  |> filter(fn: (r) => r[\"_field\"] == \"steps\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.ActivityName}))\n  |> avg_over_time(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Activities (Duration)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "alias": "Light Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "query": "from(bucket: \"tower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Activity Records\")\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r.ActivityName}))\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "minutesLightlyActive" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from(bucket: \"tower\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Activity Records\")\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r.ActivityName}))\n  |> avg_over_time(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    },
    {
     "alias": "Fair Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesFairlyActive" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Intense Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesVeryActive" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HR Zones",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "query": "from(bucket: \"tower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HR zones\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Normal\" or r[\"_field\"] == \"Peak\" or r[\"_field\"] == \"Fat Burn\" or r[\"_field\"] == \"Cardio\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r[\"_field\"]}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "expr": "from(bucket: \"tower\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HR zones\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Normal\" or r[\"_field\"] == \"Peak\" or r[\"_field\"] == \"Fat Burn\" or r[\"_field\"] == \"Cardio\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r[\"_field\"]}))\n  |> avg_over_time(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Activities Minutes",
   "type": "barchart",
   "description": "Represent the level of activity in the day",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "import \"date\"\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Activity Minutes\")\n  |> filter(fn: (r) => r._field == \"minutesFairlyActive\" or r._field == \"minutesLightlyActive\" or r._field == \"minutesSedentary\" or r._field == \"minutesVeryActive\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      Sedentary: r.minutesSedentary,\n      Light: r.minutesLightlyActive,\n      Fairly: r.minutesFairlyActive,\n      Very: r.minutesVeryActive\n  }))\n  |> yield(name: \"orderedMedian\")",
     "expr": "import \"date\"\nfrom(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Activity Minutes\")\n  |> filter(fn: (r) => r._field == \"minutesFairlyActive\" or r._field == \"minutesLightlyActive\" or r._field == \"minutesSedentary\" or r._field == \"minutesVeryActive\")\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      Sedentary: r.minutesSedentary,\n      Light: r.minutesLightlyActive,\n      Fairly: r.minutesFairlyActive,\n      Very: r.minutesVeryActive\n  }))\n  |> yield(name: \"orderedMedian\")"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "alias": "Total Distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "distance",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"distance\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n    |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Distance\"}))\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"distance\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n    |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Distance\"}))\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Calories",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "kCal" } },
   "targets": [
    {
     "alias": "Total Calories",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "calories",
     "query": "from(bucket: \"tower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"calories\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Calories\"}))\n  |> yield(name: \"median\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tz": "$TimeZone",
     "expr": "from(bucket: \"tower\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"calories\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> avg_over_time(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Calories\"}))\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Band wearing ",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 61 }
   ]
  },
  {
   "title": "Recent Activity",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"tower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Activity Records\")\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r.ActivityName}))\n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")",
     "expr": "from(bucket: \"tower\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Activity Records\")\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r.ActivityName}))\n  |> avg_over_time(every: 1h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Battery Percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceBatteryLevel",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DeviceBatteryLevel\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DeviceBatteryLevel\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> avg_over_time(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery usage rate [ d(battery level)/dt ]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"DeviceBatteryLevel\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> derivative(unit: 15m, nonNegative: false, columns: [\"_value\"], timeColumn: \"_time\")\n  |> yield(name: \"rateOfChange\")\n",
     "expr": "from(bucket: \"${bucket}\")\n  [$__range](start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"DeviceBatteryLevel\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> avg_over_time(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> derivative(unit: 15m, nonNegative: false, columns: [\"_value\"], timeColumn: \"_time\")\n  |> yield(name: \"rateOfChange\")\n"
    }
   ]
  }
 ]
}